-- CREATE DATABASE
DROP DATABASE IF EXISTS employee_trackerDB;
CREATE DATABASE employee_trackerDB;

USE employee_trackerDB;

-- DEPARTMENT TABLES
CREATE TABLE department(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE role (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(30) NOT NULL,
    SALARY DECIMAL NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    PRIMARY KEY (ID)
);

-- TABLE FOR EMPLOYEE ROLES
CREATE TABLE employee (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    MANAGER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (ID)
);


